import Head from 'next/head'
import Link from 'next/link'
import { Button } from 'antd'

const Home = () => {
  console.info('home is render...')

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>
          <Link href="/women/close.html">Close</Link>
        </div>
        <Button type="primary">Button</Button>
      </div>
    </>
  )
}

export default Home
